FROM python:3.13-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

COPY requirements-api.txt requirements-api.txt

RUN uv pip install --system -r requirements-api.txt

COPY api ./api

COPY config ./config

COPY models/register.py ./models/register.py

COPY DataPipeline ./DataPipeline

EXPOSE 1091

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "1091"]