FROM python:3.13-slim

WORKDIR /app

RUN pip install uv

COPY requirements-dashboard.txt requirements-dashboard.txt

RUN uv pip install --system -r requirements-dashboard.txt

COPY streamlit_gui ./streamlit_gui

EXPOSE 1092

CMD ["streamlit","run","streamlit_gui/app.py","--server.address","0.0.0.0","--server.port","1092"]