FROM python:3.13-slim

WORKDIR /app

RUN pip install uv

COPY requirements-train.txt requirements-train.txt

RUN uv pip install --system -r requirements-train.txt

COPY config ./config

COPY models ./models

COPY DataPipeline ./DataPipeline

COPY flow.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "flow.py"]