FROM python:3.13-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY api ./api

COPY config ./config

COPY models/register.py ./models/register.py

COPY DataPipeline ./DataPipeline

EXPOSE 1091

CMD ["uv", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "1091"]