FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY config ./config

COPY models ./models

COPY DataPipeline ./DataPipeline

COPY flow.py .

ENV PYTHONUNBUFFERED=1

CMD ["uv", "run", "flow.py"]